name: CPE Dictionary Test

on: [push, pull_request]

jobs:
  cpe-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: ./csaf_2.0/test/cpe/run_tests.sh
