name: JSON Schema Tests

on: [push, pull_request]

jobs:
  json-test_job:
    runs-on: ubuntu-latest
    name: Test JSON schemas
    steps:
    - name: Checkout repository
      uses: actions/checkout@master
    - name: Perform direct JSON schemas test
      id: json-test
      uses: ./.github/actions/json-test
    - name: Upload strict JSON schema artifact
      uses: actions/upload-artifact@v2
      with:
        name: strict-schemas
        path: |
          csaf_strict_schema.json
          provider_strict_schema.json
          aggregator_strict_schema.json
